import Footer from "./components/footer";
import Navigation from "./components/nav";
import "../styles/globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="bg">
      <body>
        <Navigation/>
        {children}
        <Footer />
      </body>
    </html>
  );
}
