import Footer from "./footer";
import Navigation from "./nav";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navigation/>
        {children}
        <Footer />
      </body>
    </html>
  );
}
